name: ic_tools
description: "ic_tools in the dart-language."
version: 2.0.1
homepage: https://github.com/levifeldman/ic_tools
platforms:
  linux:
  web:
topics:
  - crypto
  - blockchain
  - world-computer
  - internet-computer
  - agent
  


environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: 0.13.4
  #cbor: #^5.1.2 # use local package with web fix
  typed_data: ^1.3.2 
  archive: ^3.4.9 # crc32 checksum functions
  base32: 2.1.3
  crypto: 3.0.3
  ffi: 1.2.1
  js: ^0.6.7
  tuple: ^2.0.2
  ed25519_edwards: ^0.3.1
  
  # for the local cbor package  
  collection: "^1.17.2"
  #typed_data: "^1.3.0"
  hex: '^0.2.0'
  convert: "^3.1.1"
  ieee754: "^1.0.3"
  meta: "^1.9.1"

